# Generated by Django 2.2.18 on 2022-11-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221028_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='avatars/')),
                ('telephone', models.CharField(max_length=10)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userCategory')),
            ],
        ),
    ]
