# Generated by Django 2.2.18 on 2022-11-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profilesetup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileSetup',
        ),
    ]
