# Generated by Django 2.2.18 on 2022-11-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_profilesetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='User_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userCategory'),
        ),
    ]
