# Generated by Django 2.2.18 on 2022-11-10 17:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221108_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/avatars'), upload_to=''),
        ),
    ]
