# Generated by Django 2.2.18 on 2022-11-04 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_storagefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefiles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
