# Generated by Django 2.2.18 on 2022-09-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220928_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='use',
            options={},
        ),
        migrations.AlterModelTable(
            name='use',
            table=None,
        ),
    ]
