# Generated by Django 2.2.18 on 2022-09-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220928_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Use',
        ),
    ]
