# Generated by Django 2.2.18 on 2022-09-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_use'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Use',
        ),
    ]
